### ISSUE TITLE
ScreenShots

### ISSUE THREAD

**Issue by sonia3994** [jscushman/shifter#1]
Would you like to uploads some screenshots of this "shifter" ? Thanks in advance. I installed this source in Linux, but unfortunately, I do not know, how to see the output ?

**Comment by jscushman** [comment]
Hi, If you follow the instructions in the README and get to the `bin/rails server -e production` step, you should have a version running locally on your machine, which you can look at in your browser at localhost:3000 (or at whichever port it's being hosted on). Let me know if you have trouble getting to that step. I'll add some screenshots as well of the software running.

**Comment by sonia3994** [comment]
Hello jscushman,
Thanks again for your reply, I completely follow the README but I think, I still have an issue. Which indicates that, I did not install properly. Please do not mind to take a look. If you have any suggestion then please send it to me. 

jalil@Jalil-Ubunut:~/shifter$ bin/rails server -e production
/home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/application.rb:64:in `global_configuration': undefined method `reject' for #<String:0x0056266db06c58> (NoMethodError)
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/application.rb:32:in `configuration'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/application.rb:42:in `each'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/application.rb:36:in `load'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/figaro-1.1.1/lib/figaro.rb:23:in `load'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/rails/railtie.rb:5:in `block in <class:Railtie>'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:148:in `run_load_hooks!'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:96:in `instance'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:123:in `config'
	from /home/jalil/shifter/config/application.rb:17:in `<class:Application>'
	from /home/jalil/shifter/config/application.rb:10:in `<module:Shifter>'
	from /home/jalil/shifter/config/application.rb:9:in `<top (required)>'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/jalil/shifter/bin/rails:9:in `require'
	from /home/jalil/shifter/bin/rails:9:in `<top (required)>'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `load'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `call'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/client/command.rb:7:in `call'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/client.rb:28:in `run'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/bin/spring:49:in `<top (required)>'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `load'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jalil/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jalil/shifter/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by jscushman** [comment]
Hi sonia3994,

I haven't been able to replicate this error, but perhaps you can try one thing. In `config/secrets.yml`, can you try changing: `secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>`
to  `secret_key_base: ENV["SECRET_KEY_BASE"]`? Let me know if that changes anything.

Thanks,
Jeremy

**Comment by sonia3994** [comment]
Hi jscushman,
Thanks for your reply. Now I am installing the fresh copy of this code, but I can not find the file named application.yml under config/ directory. I think it should be config/secrets.yml.  So, I think in your instructions #12 or 13, they should be modified.  You can see the few screen shots. I attached here. I have a simple question that, what will be username/PASSWD for ADMIN? How to create the groups there?
<img width="783" alt="screen shot 2017-10-11 at 14 28 28" src="https://user-images.githubusercontent.com/11090484/31432724-b62ff010-ae90-11e7-8cde-d5112f8d2e76.png">
<img width="749" alt="screen shot 2017-10-11 at 14 29 00" src="https://user-images.githubusercontent.com/11090484/31432727-b6767418-ae90-11e7-88e4-8a87a5a68838.png">

**Comment by jscushman** [comment]
Hi Sonia,

Glad to see that change to the change to secrets.yml worked! The issue is that `application.yml` should be created by running `bundle exec figaro install`, but is not checked in to the repository. I will clarify this in the README. If you execute that command, you should have an `application.yml` file to place the secrets in. (Placing them in `secrets.yml` might work as well.)

The issue with the first admin is that it must be done through the rails console. After that, you can make anyone else and admin by going to their User page and checking/unchecking a box (when you're logged in as an admin). I will add this to the README as well.
1.  Run ```$ RAILS_ENV=production bundle exec rails console``` at the terminal to enter the rails console.
2. If you only have one user account, it will be `User.first`. So you can do:
```
> u = User.first
> u.admin = true
> u.save
```
and then you can exit the console with ctrl-D. At that point, the first user will be an administrator and can do anything.

**Comment by sonia3994** [comment]
Hi Cushman,
My website is working nicely. Thanks for the nice peice of code. I have a minor issue, when I used the command "rails server -e production", it does not work. When I used the command "rails server", it works nicely. Is there any difference b/w them ?

**Comment by jscushman** [comment]
That's great! Glad it's working well. The `-e production` option lets you start the server in production mode, if you have different development and production databases. See https://stackoverflow.com/questions/7154145/how-to-deploy-rails-in-production-mode, for example.

**Comment by sonia3994** [comment]
Thanks for your help.
